[tool.poetry]
name = "moo"
version = "0.0.1"
description = "multi-object optimizer"
authors = ["PuQing <me@puqing.work>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
